APP_NAME: "Library"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://rohomrutuja:1234@localhost:5432/Library?sslmode=disable"
