APP_NAME: "library_v2"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://rohomrutuja:1234@localhost:5432/library_v2?sslmode=disable"
